server:
  servlet:
    context-path: /boot
  port: 8080

jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/db_student?useUnicode=true&characterEncoding=UTF-8
  username: root
  password: root

mybatis:
  config_file: mybatis-config.xml
  mapper_path: /mapper/**.xml
  domain_package: com.example1.bootdemo.domain
